services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    volumes:
      - openwebui:/app/backend/data
    networks:
      - openwebnetwork
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-openwebui:5432/${POSTGRES_DB}
    depends_on:
      - postgres-openwebui
    
  postgres-openwebui:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-openwebui-data:/var/lib/postgresql/data
    networks:
      - openwebnetwork
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

  tunnel-openwebui:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run 
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_KEY}
    networks:
      - openwebnetwork

volumes:
  openwebui:
  postgres-openwebui-data:

networks:
  openwebnetwork:
    driver: bridge
